urlClient: http://localhost:3000
urlServer: http://localhost:8080

client:
  reset-password:
    url: booking://reset-password/

outbound:
  identity:
    client-id: "1082158409031-gag4jju0ukc0gcgoginpiamrre4fvlru.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:3000/outbound-auth"

recaptcha:
  verify-url: https://www.google.com/recaptcha/api/siteverify
  secret-key: 6LfSCS8qAAAAANeOWUAucnmphneM9MHTMbPIrGcr
  site-key: 6LfSCS8qAAAAAK8-G5UNElCtksrCCvAK10Vh-SWb

jwt:
  # Access token
  valid-duration: 400000
  accessKey: eba8aa44a64cec36cdd9b94a5f0073736bed7340144aa676e16b6a296413a5e638803f576556d662b72f2e732f870ab4359a050a087d31f0516efffe211de4e6

  # Refresh token
  refreshable-duration: 400000
  refreshKey: 9b3c2eab0e41ac67db99ed27117586d24419bbdda33321b6792dcc295cfe20bcb426be622f7aed2fb0cdf7992aa222dd9051bbb9426676243a4467556e74f6dc

  # Reset password token
  reset-password-duration: 400000
  resetKey: 5fdc5cf06bfcd73fe2540f228283cfafb56ed00ded29dac3de4a350c29717b82c4055660c36a0f9511acf43f78eda0302439813136cd52776ec875d1c7f3182e
  # Active user token
  active-user-duration: 400000
  activeKey: a3f21633fa82c60e2c70821c8dc38d568e9a2dc898a0721e72da5c1320ab7f72fba7188876920a5cbc60a960482acabe1760bb1bcfa541728ce265806ffe0f39

payment:
  vnpay:
    #    tmn-code: SRIE0UKK
    #    secret-key: YSUHAOQNTRVAVYYWKOCMBXJAEFLQQXSA
    secret-key: YSUHAOQNTRVAVYYWKOCMBXJAEFLQQXSA
    tmn-code: SRIE0UKK

    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    #    return-url: https://dev.roninhub.com/order/%s/status
    return-url: http://localhost:4200/response-transaction
    timeout: 15 # in minutes